const ACTIONS = {
  SIGN_UP_REQUEST_SUCCESSED: "SIGN_UP_REQUEST_SUCCESSED",
  SIGN_UP_REQUEST_FAILED: " SIGN_UP_REQUEST_FAILED",
  SIGN_IN_REQUEST_SUCCESSED: "SIGN_IN_REQUEST_SUCCESSED",
};

export default ACTIONS;
