const ACTIONS = {
   //user entities
   SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
   SIGN_UP_REQUEST_SUCCESSED: "SIGN_UP_REQUEST_SUCCESSED",
   SIGN_UP_REQUEST_FAILED: " SIGN_UP_REQUEST_FAILED",
   SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
   SIGN_IN_REQUEST_SUCCESSED: "SIGN_IN_REQUEST_SUCCESSED",
   SIGN_IN_REQUEST_FAILED: "SIGN_IN_REQUEST_FAILED",
   CHECK_USER_TOKEN_REQUEST_SUCCESSED: "CHECK_USER_TOKEN_REQUEST_SUCCESSED",
   CHECK_USER_TOKEN_REQUEST_FAILED: "CHECK_USER_TOKEN_REQUEST_FAILED",
   SEARCH_STOCK_REQUEST: "SEARCH_STOCK_REQUEST",
   SEARCH_STOCK_REQUEST_SUCCESSED: "SEARCH_STOCK_REQUEST_SUCCESSED",
   SEARCH_STOCK_REQUEST_FAILED: "SEARCH_STOCK_REQUEST_FAILED",
   ADD_STOCK_REQUEST_SUCCESSED: "ADD_STOCK_REQUEST_SUCCESSED",
   GET_STOCK_DETAILS_REQUEST_SUCCESSED: "GET_STOCK_DETAILS_REQUEST_SUCCESSED",
   DELETE_STOCK_REQUEST_SUCCESSED: "DELETE_STOCK_REQUEST_SUCCESSED",
   SIGN_OUT_REQUEST_SUCCESSED: "SIGN_OUT_REQUEST_SUCCESSED",

   //user view
   SET_SEARCH_KEY: "SET_SEARCH_KEY",
   CHECK_USER_TOKEN_REQUEST: "CHECK_USER_TOKEN_REQUEST",
};

export default ACTIONS;
