const ACTIONS = {
  SIGN_UP_REQUEST_SUCCESSED: "SIGN_UP_REQUEST_SUCCESSED",
  SIGN_UP_REQUEST_FAILED: " SIGN_UP_REQUEST_FAILED",
  SHOW_SIGN_UP: "SHOW_SIGN_UP",
  HIDE_CONNECT_OPTIOS: "HIDE_CONNECT_OPTIOS",
};

export default ACTIONS;
